brender/dashboard/controllers/jobs.py
import glob
import json
import os
import time
import urllib

from os import listdir
from os.path import isfile
from os.path import join
from os.path import abspath
from os.path import exists

from glob import iglob
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask import send_file
from flask import make_response
from flask import Blueprint

from dashboard import app
from dashboard import list_integers_string
from dashboard import http_server_request
# from server import RENDER_PATH

# TODO: find a better way to fill/use this variable
BRENDER_SERVER = app.config['BRENDER_SERVER']


# Name of the Blueprint
jobs = Blueprint('jobs', __name__)

def last_thumbnail(job_id):
    pass
    #render_dir = RENDER_PATH + "/" + str(job_id)
    #if not exists(render_dir):
    #    return ""

    #files = sorted(["/" + render_dir + "/" + f for f in listdir(render_dir) if  f.endswith(".thumb")])
    #return files.pop() if files else ""


@jobs.route('/')
def index():
    jobs = http_server_request('get', '/jobs')
    jobs_list = []

    for key, val in jobs.iteritems():
        val['checkbox'] = '<input type="checkbox" value="' + key + '" />'
        jobs_list.append({
            "DT_RowId": "job_" + str(key),
            "0": val['checkbox'],
            "1": key,
            "2": val['job_name'],
            "3": val['percentage_done'],
            "4": val['render_settings'],
            "5": val['status'],
            "6" : last_thumbnail(key)})
        #print(v)

    entries = json.dumps(jobs_list)

    return render_template('jobs/index.html', entries=entries, title='jobs')

@jobs.route('/<job_id>')
def job(job_id):
    print '[Debug] job_id is %s' % job_id
    job = http_server_request('get', '/jobs/' + job_id)
    #job['thumb'] = last_thumbnail(job['id'])
    # render_dir = RENDER_PATH + "/" + str(job['id']) +  '/'
    # if exists(render_dir):
    #     job['render'] = map(lambda s : join("/" + render_dir, s), \
    #                     filter(lambda s : s.endswith(".thumb"), listdir(render_dir)))
    # else:
    #     job['render'] = '#'

    return render_template('jobs/view.html', job=job)


@jobs.route('/browse/', defaults={'path': ''})
@jobs.route('/browse/<path:path>',)
def jobs_browse(path):
    if len(path) > 0:
        path = os.path.join('/browse', path)
    else:
        path = "/browse"
    print path
    path_data = http_server_request('get', path)
    return render_template('browse_modal.html',
        # items=path_data['items'],
        items_list=path_data['items_list'],
        parent_folder=path_data['parent_path'])


@jobs.route('/delete', methods=['POST'])
def jobs_delete():
    job_ids = request.form['id']
    print(job_ids)
    params = {'id': job_ids}
    jobs = http_server_request('post', '/jobs/delete', params)
    return 'done'


@jobs.route('/update', methods=['POST'])
def jobs_update():
    command = request.form['command'].lower()
    job_ids = request.form['id']
    params = {'id': job_ids,
              'status' : command}
    if command in ['start', 'stop', 'respawn', 'reset']:
        jobs = http_server_request('put',
            '/jobs', params)
        return 'done'
    else:
        return 'error', 400


@jobs.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        job_values = {
            'project_id': request.form['project_id'],
            'job_name': request.form['job_name'],
            'frame_start': request.form['frame_start'],
            'frame_end': request.form['frame_end'],
            'chunk_size': request.form['chunk_size'],
            'current_frame': request.form['frame_start'],
            'filepath': request.form['filepath'],
            'render_settings': request.form['render_settings'],
            'format' : request.form['format'],
            'status': 'running',
            'priority': 10,
            'owner': 'fsiddi'
        }

        http_server_request('post', '/jobs', job_values)

        #  flashing does not work because we use redirect_url
        #  flash('New job added!')

        return redirect(url_for('jobs.index'))
    else:
        render_settings = http_server_request('get', '/settings/render')
        projects = http_server_request('get', '/projects')
        settings = http_server_request('get', '/settings')
        return render_template('jobs/add_modal.html',
                            render_settings=render_settings,
                            settings=settings,
                            projects=projects)

brender/dashboard/controllers/main.py
import glob
import json
import os
import time
from os import listdir
from os.path import isfile, join, abspath
from glob import iglob
from flask import flash
from flask import Flask
from flask import jsonify
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask import make_response
from flask import Blueprint

from dashboard import app
from dashboard import http_server_request
from dashboard import list_integers_string
from dashboard import check_connection

from dashboard.controllers.workers import workers


# Name of the Blueprint
main = Blueprint('main', __name__)

@main.route('/')
def index():
    if check_connection() == 'online':
        return redirect(url_for('workers.index'))
    else:
        return "[error] Dashboard could not connect to server"


@main.route('/tasks/')
def tasks_index():
    tasks = http_server_request('get', '/tasks')
    tasks_list = []

    for key, val in tasks.iteritems():
        val['checkbox'] = '<input type="checkbox" value="' + key + '" />'
        tasks_list.append({
            "DT_RowId": "worker_" + str(key),
            "0": val['checkbox'],
            "1": key,
            "2": val['percentage_done'],
            "3": val['priority'],
            "4": val['status']
            })
        #print(v)

    entries = json.dumps(tasks_list)

    return render_template('tasks.html', entries=entries, title='tasks')


@main.route('/log/', methods=['GET', 'POST'])
def log():
    path = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    onlyfiles = [f for f in listdir(path) if isfile(join(path, f))]
    log_files = []
    for i in glob.iglob('*.log'):
        log_files.append(i)
    print('[Debug] %s') % log_files
    if request.method == 'POST':

        result = request.form['log_files']
        if result:
            try:
                with open(result) as log:
                        lines = log.readlines()
                return render_template('log.html',
                                       title='logs',
                                       lines=lines,
                                       result=result,
                                       log_files=log_files)
            except IOError:
                flash('Couldn\'t open file. ' +
                      'Please make sure the log file exists at ' + result)
        else:
            flash('No log to read Please input a filepath ex: ' +
                  'log.log')
    return render_template('log.html', title='logs', log_files=log_files)


@main.route('/sandbox/')
def sandbox():
    return render_template('sandbox.html', title='sandbox')

brender/dashboard/controllers/settings.py
import json
from flask import (flash,
                   render_template,
                   request,
                   Blueprint)

from dashboard import app
from dashboard import http_server_request, list_integers_string, check_connection

# Name of the Blueprint
settings = Blueprint('settings', __name__)


@settings.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        params = request.form
        http_server_request('post', '/settings', params)

    projects = http_server_request('get', '/projects')
    settings = http_server_request('get', '/settings')
    return render_template('settings/index.html',
                           title='settings',
                           settings=settings,
                           projects=projects)


@settings.route('/render/', methods=['GET'])
def render():
    render_settings = http_server_request('get', '/settings/render')
    return render_template('settings/render.html',
                           title='render settings',
                           render_settings=render_settings)


@settings.route('/status/', methods=['GET'])
def status():
    try:
        server_status = check_connection()
        server_stats = http_server_request('get', '/stats')
    except:
        server_status = 'offline'
        server_stats = ''
    return render_template('settings/status.html',
        title='server status',
        server_stats=server_stats,
        server_status=server_status)

brender/dashboard/templates/404_error.html
{% extends "layout.html" %}
{% block body %}
    <div class="page-header">
        <h1 class="page-title">Wooops : 404 error</h1>
    </div>
    <div class="row">
        <div class="span10">
            the page {{page}} was not found
        </div>
    </div>
    <hr>

{% endblock %}

brender/dashboard/templates/500_error.html
{% extends "layout.html" %}
{% block body %}
  <div class="page-header">
    <h1 class="page-title">Brender Server Error</h1>
  </div>
  <div id='content' class="row">
    {{error | safe }}
  </div>
  <hr>

{% endblock %}

brender/dashboard/templates/browse_modal.html
<ul class="files">
  {% if parent_folder %}
  <li><a class="folder" href="{{parent_folder}}">..</a></li>
  {% endif %}
  {% for item in items_list %}
  <li><a class="{{item[2]}}" href="{{item[1]}}">{{item[0]}}</a></li>
  {% endfor %}
</ul>


<script>
  $(document).ready(function() {

    $('#brenderModalLabel').text('Select a blendfile');

    // Support for AJAX loaded modal window.
    // Focuses on first input textbox after it loads the window.
    $('.folder').click(function(e) {
      e.preventDefault();
      var url = '/jobs/browse/' + $(this).attr('href');
      $.get(url, function(data) {
        $('.modal-body').html(data);
      });
    });

    $('.blendfile').click(function(e) {
      e.preventDefault();
      var url = '/jobs/browse/' + $(this).attr('href');
      $(this).parent().siblings().children('a').removeClass('active');
      $(this).addClass('active');
      $('#modal_variable').val($(this).attr('href'));

    });

    $('.select-file').click(function(e) {
      e.preventDefault();
      var url = '/jobs/add';
      $.get(url, function(data) {
        $('.modal-body').html(data);
      });
      $('.modal-footer').children('.btn-primary').text('Add Job');
    });

  });

</script>

brender/dashboard/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>brender - friendly render farm</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="{{ url_for('static', filename='js/jquery-1.7.2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.brender.js') }}"></script>
    <script src="{{ url_for('static', filename='js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.readmore-readless.js') }}" type="text/javascript"></script>
    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'> -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">
<!--     <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css"> -->
    <link href="{{ url_for('static', filename='css/brender.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/dataTables.bootstrap.css') }}" rel="stylesheet">

    <!-- IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='ico/favicon.ico') }}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    {% block modal %}

    <div class="modal fade" id="brenderModal" tabindex="-1" role="dialog" aria-labelledby="brenderModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="brenderModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">

          </div>
          <div class="modal-footer">
            <input type="hidden" id="modal_variable" name="modal_variable" value="">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" onclick="$('.modal-body > form').submit();" >Submit job</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    {% endblock %}

    <header class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">b<strong>render</strong></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <nav class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li {% if title == 'workers': %} class="active"{% endif %}>
              <a href="{{ url_for('workers.index') }}">Workers</a>
            </li>
            <li {% if title == 'jobs': %} class="active"{% endif %}>
              <a href="{{ url_for('jobs.index') }}">Jobs</a>
            </li>
            <li {% if title == 'tasks': %} class="active"{% endif %}>
              <a href="{{ url_for('main.tasks_index') }}">Tasks</a>
            </li>
            <li>
              <a href="#" data-toggle="modal" modal="{{ url_for('jobs.add') }}" data-target="#addJobModal">Add Job</a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Server <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('settings.status') }}">Status</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('settings.index') }}">Settings</a></li>
                <li><a href="{{ url_for('settings.render') }}">Render Settings</a></li>
                <li><a href="{{ url_for('projects.index') }}">Projects</a></li>
                <li><a href="{{ url_for('main.log') }}">Logs</a></li>
                <li><a href="{{ url_for('main.sandbox') }}">Sandbox</a></li>
              </ul>
            </li>
          </ul>
        </nav><!-- /.navbar-collapse -->
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% for message in get_flashed_messages() %}
          <div class="alert alert-warning">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{ message }}
            </div>
          {% endfor %}
          {% block body %}{% endblock %}
        </div>
      </div>
      <hr>
      <footer>
          <p>brender 2.0 is distributed under GPL 2.0 license and was originally developed by Olivier Amrein and Francesco Siddi.</p>
      </footer>

    </div> <!-- /container -->

  {% block footer_scripts %}{% endblock %}

  <script>
  $(document).ready(function() {
    // Support for AJAX loaded modal window.
    // Focuses on first input textbox after it loads the window.
    $('[data-toggle="modal"]').click(function(e) {
      e.preventDefault();
      var url = $(this).attr('modal');
      /*
      if (url.indexOf('#') == 0) {
        $(url).modal('open');
      } else {
        $.get(url, function(data) {
          $('<div class="modal fade">' + data + '</div>').modal();
        }).success(function() {
            $('input:text:visible:first').focus();
        });
      }*/

      $.get(url, function(data) {
        $('.modal-body').html(data);
      });

      $('.modal-footer').children('.btn-primary').text('Add Job');
      $('#brenderModal').modal('show');
    });

  });

  </script>

  </body>
</html>

brender/dashboard/templates/log.html
{% extends "layout.html" %}
{% block body %}
    <h1 class="page-title">{{title}}</h1>
    <hr>
    <div class="row">
        <form action="/log/" method="POST">
            <div class="input-group span2">
                <select name="log_files" class="form-control">
                    {% if log_files|length == 0 %}
                    <option value="No Log">No Log Files</option>
                    {% endif %}
                    {% for file in log_files  %}
                        <option value="{{file}}" {% if file in request.form['log_files'] %}selected="selected"{% endif %}  >{{file}}</option>
                    {% endfor %}
                </select>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default {% if log_files|length == 0 %} disabled {% endif %}">View Log</button>
                </span>
            </div>
        </form>
    </div>
    <div id="log">
        <hr>
        {% for line in lines %}
            <p>{{ line }}</p>
        {% endfor %}
        {% if lines %}
        <hr>
        {% endif %}
    </div>

{% endblock %}

brender/dashboard/templates/sandbox.html
{% extends "layout.html" %}
{% block footer_scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        $(document).on("click", "#test_render", function() {
                $.post('/workers/render_chunk', function() {
                    console.log('Worker is running test command');
                });
        });
    });
</script>
{% endblock %}

{% block body %}
    <div class="page-header">
        <h1 class="page-title">{{title}}</h1>
    </div>
    <div class="row">
        <div class="span10">
            This is the place where the future of brender lives.<br/>
        </div>
    </div>
    <div class="row">
        <div class="span10">
            <p><div id="test_render" class="btn">Make a test render on client id=1</div></p>
        </div>
    </div>

{% endblock %}

brender/dashboard/templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
    <form action="{{ url_for('clients') }}" method=post class=add-entry>
      <dl>
        <dt>Title:
        <dd><input type=text size=30 name=title>
        <dt>Text:
        <dd><textarea name=text rows=5 cols=40></textarea>
        <dd><input type=submit value=Share>
      </dl>
    </form>
  <ul class=entries>
  {{ entries }}
  </ul>
{% endblock %}

brender/dashboard/templates/tasks.html
{% extends "layout.html" %}
{% block footer_scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        var tasksTable = $('#tasks').dataTable({
            "bProcessing": true,
            "iDisplayLength": 25,
            "aaData": {{ entries | safe }},
            "aoColumns": [
                { "bSortable": false },
                null,
                null,
                null,
                null
            ],

            "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
                var btn_status = "";
                if (aData[3] == "offline"){
                    $('td:eq(3)', nRow).html('<span class="label label-important">offline</apn>');
                    btn_status = "disabled";
                } else if (aData[3] == "online"){
                    $('td:eq(3)', nRow).html('<span class="label label-success">online</apn>');
                }

                if (aData[4] == "enabled"){
                    $('td:eq(4)', nRow).html('<span class="status-toggle btn btn-mini btn-success ' + btn_status + '">enabled</span>');
                } else if (aData[4] == "disabled"){
                    $('td:eq(4)', nRow).html('<span class="status-toggle btn btn-mini btn-warning ' + btn_status + '">disabled</span>');
                }
            }
        });

        $(document).on("click", ".status-toggle", function() {
            var status = $(this).html();
            var tableRow = $(this).parents("tr");
            var rowPosition = tasksTable.fnGetPosition(tableRow[0]);
            var clientId = tableRow.attr("id").split("_")[1];

            if (status == 'enabled') {
                data = {id : clientId, status: 'disabled'};
                $.post('/workers/edit', data, function() {
                    console.log('Worker is now disabled');
                    tasksTable.fnUpdate('disabled', rowPosition ,4);
                });
            } else if (status == 'disabled') {
                data = {id : clientId, status: 'enabled'};
                $.post('/workers/edit', data, function() {
                    console.log('Worker is now enabled');
                    tasksTable.fnUpdate('enabled', rowPosition ,4);
                });
            }
        });
        $(document).on("click", ".check-all", function(){
            $("table input[type=checkbox]").attr('checked', $(this).is(':checked'));
        });
    });
</script>
{% endblock %}
{% block body %}
    <h1 class="page-title">{{title}}</h1>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div id="clients-disable-all" class="btn btn-warning">Disable All</div>
            <div id="clients-enable-all" class="btn btn-success">EnableAll</div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-condensed" id="tasks">
                <thead>
                    <tr>
                        <th width="10%"><input class="check-all" type="checkbox"></th>
                        <th width="30%">Thumbnail</th>
                        <th width="30%">Completion</th>
                        <th width="20%">Priority</th>
                        <th width="20%">Status</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <th>Thumbnail - Job ID</th>
                        <th>Completion</th>
                        <th>Priority</th>
                        <th>Status</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

{% endblock %}