brender/dashboard/controllers/projects.py
import json

from flask import flash
from flask import render_template
from flask import request
from flask import Blueprint
from flask import url_for
from flask import redirect

from dashboard import app
from dashboard import list_integers_string
from dashboard import check_connection
from dashboard import http_server_request

projects = Blueprint('projects', __name__)


@projects.route('/')
def index():
    #projects = http_server_request('get', '/projects')
    settings = http_server_request('get', '/settings')

    projects = http_server_request('get', '/projects')

    return render_template('projects/index.html',
        projects=projects,
        settings=settings,
        title='projects')


@projects.route('/update/<project_id>', methods=['POST'])
def update(project_id):

    params = dict(
        path_server=request.form['path_server'],
        path_linux=request.form['path_linux'],
        path_win=request.form['path_win'],
        path_osx=request.form['path_osx'],
        render_path_server=request.form['render_path_server'],
        render_path_linux=request.form['render_path_linux'],
        render_path_win=request.form['render_path_win'],
        render_path_osx=request.form['render_path_osx'])

    projects = http_server_request('put', '/projects/' + project_id, params)
    print projects
    # http_server_request('get', '/projects/update', params)

    return redirect(url_for('projects.index'))


@projects.route('/delete/<project_id>', methods=['GET', 'POST'])
def delete(project_id):
    http_server_request('delete', '/projects/' + project_id)
    #http_server_request('get', '/projects/delete/' + project_id)
    return redirect(url_for('projects.index'))


@projects.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        params = dict(
            name=request.form['name'],
            path_server=request.form['path_server'],
            path_linux=request.form['path_linux'],
            path_win=request.form['path_win'],
            path_osx=request.form['path_osx'],
            render_path_server=request.form['render_path_server'],
            render_path_linux=request.form['render_path_linux'],
            render_path_win=request.form['render_path_win'],
            render_path_osx=request.form['render_path_osx'],
            is_active=request.form['set_project_option'])
        http_server_request('post', '/projects', params)
        return redirect(url_for('projects.index'))
    else:
        render_settings = http_server_request('get', '/settings/render')
        projects = http_server_request('get', '/projects')
        settings = http_server_request('get', '/settings')
        return render_template('projects/add_modal.html',
                        render_settings=render_settings,
                        settings=settings,
                        projects=projects)

brender/dashboard/templates/projects/add_modal.html
<form id="addProject" role="form" action="{{ url_for('projects.add') }}" method=post>
<input name="project_id" type="hidden" value="{{project}}">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label for="name">project Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="project name" required="">
            </div>
        </div>
    </div> <!-- end project name row -->
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="path_server">Project path on the server</label>
                <input type="text" class="form-control" id="path_server" name="path_server" placeholder="/shared/<project_name>" required="">
            </div>
        </div>
    </div> <!-- end path server row -->
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="path_linux">Project path on Linux workers</label>
                <input type="text" class="form-control" id="path_linux" name="path_linux" placeholder="/local/storage/<project_name>" required="">
            </div>
        </div>
    </div> <!-- end path linux row -->
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="path_win">Project path on Windows workers</label>
                <input type="text" class="form-control" id="path_win" name="path_win" placeholder="/local/storage/<project_name>" required="">
            </div>
        </div>
    </div> <!-- end path windows row -->
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="path_osx">Project path on OSX workers</label>
                <input type="text" class="form-control" id="path_osx" name="path_osx" placeholder="/local/storage/<project_name>" required="">
            </div>
        </div>
    </div> <!-- end path osx row -->


    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="render_path_server">Shared render path on the server</label>
                <input type="text" class="form-control" id="render_path_server" name="render_path_server" placeholder="/shared/<project_name>" required="">
            </div>
        </div>
    </div> <!-- end path server row -->
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="render_path_linux">Shared render path on Linux workers</label>
                <input type="text" class="form-control" id="render_path_linux" name="render_path_linux" placeholder="/local/storage/<project_name>" required="">
            </div>
        </div>
    </div> <!-- end path linux row -->
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="render_path_win">Shared render path on Windows workers</label>
                <input type="text" class="form-control" id="render_path_win" name="render_path_win" placeholder="/local/storage/<project_name>" required="">
            </div>
        </div>
    </div> <!-- end path windows row -->
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="render_path_osx">Shared render path on OSX workers</label>
                <input type="text" class="form-control" id="render_path_osx" name="render_path_osx" placeholder="/local/storage/<project_name>" required="">
            </div>
        </div>
    </div> <!-- end path osx row -->

    <div class="row col-md-12">
        <div class="form-group">
            <label for="set_project_option"> Set <i id="new_project_name"></i> as active project?</label>
                <select class="form-control" name="set_project_option">
                    <option>True</option>
                    {% if projects %}
                    <option selected>False</option>
                    {% endif %}
                </select>
        </div>
    </div> <!-- end set active row -->        
    <i class="clearfix"></i>
</form>

<script>
$(document).ready(function() {
    $('#brenderModalLabel').text('Add project');
    $('.modal-footer').children('.btn-primary').text('Add project');
    $('#name').keyup(function(){
     $('#new_project_name').text($(this).val());
  });
});
</script>

brender/dashboard/templates/projects/index.html
{% extends "layout.html" %}
{% block footer_scripts %}
<script>
$('[data-toggle="popover"]').popover({
    html: true,
    trigger: 'click',
    'placement': 'top',
    container: 'body',
    animation: true
});
</script>
{% endblock %}
{% block body %}
  <h1 class="pull-left page-title">{{title}}</h1>
  <a href="#" class="btn btn-success pull-right" data-toggle="modal" modal="{{ url_for('projects.add') }}" data-target="#addProjectModal">Add Project</a>
  <div class="clearfix"></div>
  <hr>
  {% for project in projects %}
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                {% if project == settings['active_project'] %}<span class="glyphicon glyphicon-bookmark"></span>{% endif %} {{projects[project]['name']}}
                <a id="pop-{{project}}" 
                    href="#" 
                    class="glyphicon glyphicon-remove pull-right" 
                    data-toggle="popover",
                    title="<p class='text-danger'>Delete {{projects[project]['name']}}?</p>"
                data-content="
                    <a href='/projects/delete/{{ project }}' class='btn btn-danger'>Ok</a>
                    <a onclick=&quot;$('#pop-{{project}}').popover('hide');&quot; class='btn btn-default'>Cancel</a>"
                ></a>
        <div class="clearfix"></div>
            </h3>
        </div>
        <div class="panel-body">
          <form class="form-horizontal" role="form" method="post" action="{{ url_for('projects.update', project_id=project) }}">
            <div class="form-group">
              <label for="path_server" class="col-sm-2 control-label">Path Server</label>
              <div class="col-sm-10">
                  <input name="path_server" type="text" class="form-control" value="{{projects[project]['path_server']}}">
              </div>
            </div>
            <div class="form-group">
              <label for="path_linux" class="col-sm-2 control-label">Path Linux</label>
              <div class="col-sm-10">
                  <input name="path_linux" type="text" class="form-control" value="{{projects[project]['path_linux']}}">
              </div>
            </div>
       <div class="form-group">
              <label for="path_win" class="col-sm-2 control-label">Path Windows</label>
              <div class="col-sm-10">
                  <input name="path_win" type="text" class="form-control" value="{{projects[project]['path_win']}}">
              </div>
            </div>
            <div class="form-group">
              <label for="path_osx" class="col-sm-2 control-label">Path OSX</label>
              <div class="col-sm-10">
                  <input name="path_osx" type="text" class="form-control" value="{{projects[project]['path_osx']}}">
              </div>
            </div>



            <div class="form-group">
              <label for="render_path_server" class="col-sm-2 control-label">Shared Render Path Server</label>
              <div class="col-sm-10">
                  <input name="render_path_server" type="text" class="form-control" value="{{projects[project]['render_path_server']}}">
              </div>
            </div>
            <div class="form-group">
              <label for="render_path_linux" class="col-sm-2 control-label">Shared Render Path Linux</label>
              <div class="col-sm-10">
                  <input name="render_path_linux" type="text" class="form-control" value="{{projects[project]['render_path_linux']}}">
              </div>
            </div>
       <div class="form-group">
              <label for="render_path_win" class="col-sm-2 control-label">Shared Render Path Windows</label>
              <div class="col-sm-10">
                  <input name="render_path_win" type="text" class="form-control" value="{{projects[project]['render_path_win']}}">
              </div>
            </div>
            <div class="form-group">
              <label for="render_path_osx" class="col-sm-2 control-label">Shared Render Path OSX</label>
              <div class="col-sm-10">
                  <input name="render_path_osx" type="text" class="form-control" value="{{projects[project]['render_path_osx']}}">
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Update</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
{% endblock %}